# This is a basic workflow to help you get started with Actions

name: Add a new GitHub Project card linked to a GitHub issue to the specified project column
on: [issues, pull_request]
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: yuta1024/cards-moving-automation@v1
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          project: 'My_sample_project'
          from_column: 'To do'
          to_column: 'In progress'
