
# This is a basic workflow to help you get started with Actions

name: yyyya new GitHub Project card linked to a GitHub issue to the specified project column
on: [issues]
jobs:
  automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && github.event.action == 'unassigned'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/shrikantgond/git_projectDemo/projects/1
        GITHUB_PROJECT_COLUMN_NAME: To do
    - name: move-inprogress-column
      uses: yuta1024/cards-moving-automation@v1
      if: github.event_name == 'issues' && github.event.action == 'assigned'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        project: 'My_sample_project'
        from_column: To do
        to_column: 'In progress'
